/**
 * Roger Ebert's Great Movies — full list of titles + years.
 * Used by /api/admin/seed-ebert to search TMDB and seed the movies table.
 */
export const EBERT_FILMS: { title: string; year: number }[] = [
  { title: "12 Angry Men", year: 1957 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "25th Hour", year: 2002 },
  { title: "3 Women", year: 1977 },
  { title: "8½", year: 1963 },
  { title: "Ace in the Hole", year: 1951 },
  { title: "Adaptation.", year: 2002 },
  { title: "The Adventures of Robin Hood", year: 1938 },
  { title: "After Dark, My Sweet", year: 1990 },
  { title: "After Hours", year: 1985 },
  { title: "The Age of Innocence", year: 1993 },
  { title: "Aguirre, the Wrath of God", year: 1972 },
  { title: "A.I. Artificial Intelligence", year: 2001 },
  { title: "Ali: Fear Eats the Soul", year: 1974 },
  { title: "Alien", year: 1979 },
  { title: "All About Eve", year: 1950 },
  { title: "Amadeus", year: 1984 },
  { title: "Amarcord", year: 1973 },
  { title: "Annie Hall", year: 1977 },
  { title: "The Apartment", year: 1960 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Pather Panchali", year: 1955 },
  { title: "Aparajito", year: 1956 },
  { title: "Apur Sansar", year: 1959 },
  { title: "Army of Shadows", year: 1969 },
  { title: "Atlantic City", year: 1980 },
  { title: "Au Hasard Balthazar", year: 1966 },
  { title: "Au Revoir les Enfants", year: 1987 },
  { title: "An Autumn Afternoon", year: 1962 },
  { title: "Babel", year: 2006 },
  { title: "Badlands", year: 1973 },
  { title: "The Ballad of Narayama", year: 1983 },
  { title: "The Band Wagon", year: 1953 },
  { title: "The Bank Dick", year: 1940 },
  { title: "Baraka", year: 1992 },
  { title: "Barry Lyndon", year: 1975 },
  { title: "The Battle of Algiers", year: 1966 },
  { title: "Battleship Potemkin", year: 1925 },
  { title: "Beat the Devil", year: 1953 },
  { title: "Beauty and the Beast", year: 1946 },
  { title: "Being There", year: 1979 },
  { title: "Belle de Jour", year: 1967 },
  { title: "La Belle Noiseuse", year: 1991 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "Bicycle Thieves", year: 1948 },
  { title: "The Big Heat", year: 1953 },
  { title: "The Big Lebowski", year: 1998 },
  { title: "The Big Sleep", year: 1946 },
  { title: "Blade Runner", year: 1982 },
  { title: "Blow-Up", year: 1966 },
  { title: "The Blue Kite", year: 1993 },
  { title: "Bob le Flambeur", year: 1956 },
  { title: "Body Heat", year: 1981 },
  { title: "Bonnie and Clyde", year: 1967 },
  { title: "Breathless", year: 1960 },
  { title: "Bride of Frankenstein", year: 1935 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "Bring Me the Head of Alfredo Garcia", year: 1974 },
  { title: "The Cabinet of Dr. Caligari", year: 1920 },
  { title: "Caché", year: 2005 },
  { title: "Casablanca", year: 1942 },
  { title: "Cat People", year: 1942 },
  { title: "La Cérémonie", year: 1995 },
  { title: "Un Chien Andalou", year: 1929 },
  { title: "Children of Paradise", year: 1945 },
  { title: "Chimes at Midnight", year: 1965 },
  { title: "Chinatown", year: 1974 },
  { title: "A Christmas Story", year: 1983 },
  { title: "Citizen Kane", year: 1941 },
  { title: "City Lights", year: 1931 },
  { title: "Cléo from 5 to 7", year: 1962 },
  { title: "The Color Purple", year: 1985 },
  { title: "Come and See", year: 1985 },
  { title: "Contact", year: 1997 },
  { title: "The Conversation", year: 1974 },
  { title: "Cool Hand Luke", year: 1967 },
  { title: "Cries and Whispers", year: 1972 },
  { title: "Crimes and Misdemeanors", year: 1989 },
  { title: "Crumb", year: 1994 },
  { title: "Dark City", year: 1998 },
  { title: "Day for Night", year: 1973 },
  { title: "Days of Heaven", year: 1978 },
  { title: "The Dead", year: 1987 },
  { title: "Departures", year: 2008 },
  { title: "Detour", year: 1945 },
  { title: "Diary of a Country Priest", year: 1951 },
  { title: "The Discreet Charm of the Bourgeoisie", year: 1972 },
  { title: "Diva", year: 1981 },
  { title: "Do the Right Thing", year: 1989 },
  { title: "Dog Day Afternoon", year: 1975 },
  { title: "Don't Look Now", year: 1973 },
  { title: "Double Indemnity", year: 1944 },
  { title: "The Double Life of Véronique", year: 1991 },
  { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
  { title: "Duck Soup", year: 1933 },
  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "The Earrings of Madame de...", year: 1953 },
  { title: "Easy Rider", year: 1969 },
  { title: "El Norte", year: 1983 },
  { title: "El Topo", year: 1970 },
  { title: "The Enigma of Kaspar Hauser", year: 1974 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "Exotica", year: 1994 },
  { title: "The Exterminating Angel", year: 1962 },
  { title: "Fanny and Alexander", year: 1982 },
  { title: "Fargo", year: 1996 },
  { title: "The Firemen's Ball", year: 1967 },
  { title: "Fitzcarraldo", year: 1982 },
  { title: "Five Easy Pieces", year: 1970 },
  { title: "Floating Weeds", year: 1959 },
  { title: "Forbidden Games", year: 1952 },
  { title: "The 400 Blows", year: 1959 },
  { title: "French Cancan", year: 1954 },
  { title: "Gates of Heaven", year: 1978 },
  { title: "The General", year: 1926 },
  { title: "The Godfather", year: 1972 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "Goldfinger", year: 1964 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "The Good, the Bad and the Ugly", year: 1966 },
  { title: "GoodFellas", year: 1990 },
  { title: "The Gospel According to St. Matthew", year: 1964 },
  { title: "Grand Illusion", year: 1937 },
  { title: "The Grapes of Wrath", year: 1940 },
  { title: "Grave of the Fireflies", year: 1988 },
  { title: "The Great Dictator", year: 1940 },
  { title: "Greed", year: 1924 },
  { title: "Groundhog Day", year: 1993 },
  { title: "The Hairdresser's Husband", year: 1990 },
  { title: "Harakiri", year: 1962 },
  { title: "A Hard Day's Night", year: 1964 },
  { title: "Hoop Dreams", year: 1994 },
  { title: "House of Games", year: 1987 },
  { title: "Howards End", year: 1992 },
  { title: "The Hustler", year: 1961 },
  { title: "Ikiru", year: 1952 },
  { title: "In a Lonely Place", year: 1950 },
  { title: "In Cold Blood", year: 1967 },
  { title: "It's a Wonderful Life", year: 1946 },
  { title: "Jaws", year: 1975 },
  { title: "JFK", year: 1991 },
  { title: "Jules and Jim", year: 1962 },
  { title: "Juliet of the Spirits", year: 1965 },
  { title: "Killer of Sheep", year: 1978 },
  { title: "The Killing", year: 1956 },
  { title: "Kind Hearts and Coronets", year: 1949 },
  { title: "King Kong", year: 1933 },
  { title: "L'Atalante", year: 1934 },
  { title: "L'Avventura", year: 1960 },
  { title: "L.A. Confidential", year: 1997 },
  { title: "La Dolce Vita", year: 1960 },
  { title: "The Lady Eve", year: 1941 },
  { title: "The Last Picture Show", year: 1971 },
  { title: "Last Tango in Paris", year: 1972 },
  { title: "The Last Temptation of Christ", year: 1988 },
  { title: "Last Year at Marienbad", year: 1961 },
  { title: "Late Spring", year: 1949 },
  { title: "Laura", year: 1944 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "Le Samouraï", year: 1967 },
  { title: "Leaving Las Vegas", year: 1995 },
  { title: "Léolo", year: 1992 },
  { title: "The Leopard", year: 1963 },
  { title: "The Life and Death of Colonel Blimp", year: 1943 },
  { title: "The Long Goodbye", year: 1973 },
  { title: "Lost in Translation", year: 2003 },
  { title: "M", year: 1931 },
  { title: "Magnolia", year: 1999 },
  { title: "Make Way for Tomorrow", year: 1937 },
  { title: "The Maltese Falcon", year: 1941 },
  { title: "A Man Escaped", year: 1956 },
  { title: "The Man Who Shot Liberty Valance", year: 1962 },
  { title: "Man with a Movie Camera", year: 1929 },
  { title: "The Manchurian Candidate", year: 1962 },
  { title: "Manhattan", year: 1979 },
  { title: "The Marriage of Maria Braun", year: 1979 },
  { title: "McCabe & Mrs. Miller", year: 1971 },
  { title: "Mean Streets", year: 1973 },
  { title: "Metropolis", year: 1927 },
  { title: "Mishima: A Life in Four Chapters", year: 1985 },
  { title: "Mon Oncle", year: 1958 },
  { title: "Monsieur Hulot's Holiday", year: 1953 },
  { title: "Moolaadé", year: 2004 },
  { title: "Moonstruck", year: 1987 },
  { title: "Mulholland Drive", year: 2001 },
  { title: "My Dinner with Andre", year: 1981 },
  { title: "My Fair Lady", year: 1964 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "Mystery Train", year: 1989 },
  { title: "Nanook of the North", year: 1922 },
  { title: "Nashville", year: 1975 },
  { title: "Network", year: 1976 },
  { title: "The Night of the Hunter", year: 1955 },
  { title: "Nights of Cabiria", year: 1957 },
  { title: "Nosferatu", year: 1922 },
  { title: "Nosferatu the Vampyre", year: 1979 },
  { title: "Notorious", year: 1946 },
  { title: "On the Waterfront", year: 1954 },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
  { title: "Ordet", year: 1955 },
  { title: "Orpheus", year: 1950 },
  { title: "Out of the Past", year: 1947 },
  { title: "Pan's Labyrinth", year: 2006 },
  { title: "Pandora's Box", year: 1929 },
  { title: "Paris, Texas", year: 1984 },
  { title: "The Passion of Joan of Arc", year: 1928 },
  { title: "Paths of Glory", year: 1957 },
  { title: "Patton", year: 1970 },
  { title: "Peeping Tom", year: 1960 },
  { title: "Persona", year: 1966 },
  { title: "Pickpocket", year: 1959 },
  { title: "Picnic at Hanging Rock", year: 1975 },
  { title: "Pixote", year: 1981 },
  { title: "Planes, Trains and Automobiles", year: 1987 },
  { title: "PlayTime", year: 1967 },
  { title: "The Producers", year: 1967 },
  { title: "Psycho", year: 1960 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "Raging Bull", year: 1980 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "Raise the Red Lantern", year: 1991 },
  { title: "Ran", year: 1985 },
  { title: "Rashomon", year: 1950 },
  { title: "Rear Window", year: 1954 },
  { title: "Rebel Without a Cause", year: 1955 },
  { title: "Red Beard", year: 1965 },
  { title: "The Red Shoes", year: 1948 },
  { title: "Rififi", year: 1955 },
  { title: "The Right Stuff", year: 1983 },
  { title: "Rio Bravo", year: 1959 },
  { title: "The Rules of the Game", year: 1939 },
  { title: "Samurai Rebellion", year: 1967 },
  { title: "Sansho the Bailiff", year: 1954 },
  { title: "Santa Sangre", year: 1989 },
  { title: "Saturday Night Fever", year: 1977 },
  { title: "Say Anything...", year: 1989 },
  { title: "Scarface", year: 1983 },
  { title: "Schindler's List", year: 1993 },
  { title: "The Searchers", year: 1956 },
  { title: "Secrets & Lies", year: 1996 },
  { title: "Se7en", year: 1995 },
  { title: "Seven Samurai", year: 1954 },
  { title: "The Seventh Seal", year: 1957 },
  { title: "Shadow of a Doubt", year: 1943 },
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Shining", year: 1980 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Singin' in the Rain", year: 1952 },
  { title: "Snow White and the Seven Dwarfs", year: 1937 },
  { title: "Solaris", year: 1972 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "The Spirit of the Beehive", year: 1973 },
  { title: "Spirited Away", year: 2001 },
  { title: "Spring, Summer, Fall, Winter... and Spring", year: 2003 },
  { title: "Star Wars", year: 1977 },
  { title: "Strangers on a Train", year: 1951 },
  { title: "Stroszek", year: 1977 },
  { title: "Sunrise: A Song of Two Humans", year: 1927 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "Sweet Smell of Success", year: 1957 },
  { title: "Taxi Driver", year: 1976 },
  { title: "The Thin Man", year: 1934 },
  { title: "The Third Man", year: 1949 },
  { title: "Three Colours: Blue", year: 1993 },
  { title: "Three Colours: White", year: 1994 },
  { title: "Three Colours: Red", year: 1994 },
  { title: "This Is Spinal Tap", year: 1984 },
  { title: "Through a Glass Darkly", year: 1961 },
  { title: "Tokyo Story", year: 1953 },
  { title: "Touch of Evil", year: 1958 },
  { title: "The Treasure of the Sierra Madre", year: 1948 },
  { title: "Trouble in Paradise", year: 1932 },
  { title: "Ugetsu", year: 1953 },
  { title: "Unforgiven", year: 1992 },
  { title: "Vertigo", year: 1958 },
  { title: "Viridiana", year: 1961 },
  { title: "Vivre Sa Vie", year: 1962 },
  { title: "Waking Life", year: 2001 },
  { title: "Walkabout", year: 1971 },
  { title: "Werckmeister Harmonies", year: 2000 },
  { title: "West Side Story", year: 1961 },
  { title: "The Wild Bunch", year: 1969 },
  { title: "Wings of Desire", year: 1987 },
  { title: "The Wizard of Oz", year: 1939 },
  { title: "Woman in the Dunes", year: 1964 },
  { title: "A Woman Under the Influence", year: 1974 },
  { title: "Woodstock", year: 1970 },
  { title: "Yankee Doodle Dandy", year: 1942 },
  { title: "Yellow Submarine", year: 1968 },
  { title: "Yojimbo", year: 1961 },
  // Decalogue episodes
  { title: "Dekalog", year: 1988 },
  // Up documentary series
  { title: "Seven Up!", year: 1964 },
  { title: "21 Up", year: 1977 },
  { title: "28 Up", year: 1984 },
  { title: "35 Up", year: 1991 },
  { title: "42 Up", year: 1998 },
  // Buster Keaton features
  { title: "The General", year: 1926 },
  { title: "Sherlock Jr.", year: 1924 },
  { title: "Our Hospitality", year: 1923 },
  { title: "The Navigator", year: 1924 },
  { title: "Seven Chances", year: 1925 },
  { title: "Steamboat Bill, Jr.", year: 1928 },
];
